### ISSUE TITLE
ошибка при установке

### ISSUE THREAD

**Issue by PyWebSol** [DataSC3/noblack-mail#11]
NameError: name 'COLOR_CODE' is not defined

**Comment by DataSC3** [comment]
Здравствуйте, обновите софт (удалите старую и переустановите), код исправен.

**Comment by PyWebSol** [comment]
модуля src.config не существует
![изображение](https://github.com/DataSC3/noblack-mail/assets/135124146/91bf745e-ca6b-450c-8038-959168ee61e5)
![изображение](https://github.com/DataSC3/noblack-mail/assets/135124146/8eb92b30-069c-4f41-8243-a25ebd68cca0)

**Comment by PyWebSol** [comment]
обновил, не помогло. не могу импортировать src и модули из этой папки

**Comment by PyWebSol** [comment]
закинул все в один файл и заработало

**Comment by DataSC3** [comment]
> закинул все в один файл и заработало

Возможно в начале установки возникла проблема, поэтому не правильно работали модули поддержки. Спасибо)
