### ISSUE TITLE
лимиты...

### ISSUE THREAD

**Issue by SlavikDoxit** [DataSC3/noblack-mail#14]
что обозначают лимиты? что будет когда они кончатся? очень пугает этот факт, сервис позволяет только 16 использований?

**Comment by DataSC3** [comment]
Здравствуйте, сервис варьирует лимиты от вашей активности. Лимиты выдаются серверами и в коде убрать их невозможно.

**Софт предоставляет 15-20 лимитов в день (24ч)** после истечении этой времени они обновяться и снова вернутся 15-20 лимитов.
