### ISSUE TITLE
No such file or directory

### ISSUE THREAD

**Issue by SigmaChushpan** [DataSC3/noblack-mail#16]
/data/data/com.termux/files/usr/bin/python3: can't open file '/data/data/com.termux/files/home/noblack-mail.py': [Errno 2] No such file or directory
![Screenshot_20240624-091209](https://github.com/DataSC3/noblack-mail/assets/173634752/d5702f59-5529-4acd-97eb-7bab76327ea6)

**Comment by Eeptao** [comment]
bash TigerVirus.shcd TigerVirusgit clone https://github.com/Devil-Tigers/TigerVirus.git
pkg install git -yapt updateapt upgrade -y
