### ISSUE TITLE
Dox

### ISSUE THREAD

**Issue by maxonmq** [DataSC3/noblack-mail#9]

**Comment by ZoTrain** [comment]
+7 995 902-11-22

**Comment by SlavikDoxit** [comment]
not working, types that my version is old but link for new don't working

не работает. пишет что вышла новая версия, а ссылка на нее не работает, помогите пожалуйста

**Comment by Hakermarker** [comment]
+79088359347

**Comment by DataSC3** [comment]
> не работает, пишет, что моя версия старая, но ссылка на новую не работает
> 
> не работает. пишет что вышла новая версия, ссылка на нее не работает, помогите пожалуйста



Hello, please provide us with screenshots (photos) where the error is shown. Redirection to new installation works correctly.

**Comment by DataSC3** [comment]
> +79088359347

Вероятно не туда опубликовали номер)
